window.EASEBIZ_VALIDATION_RULES = {
    roleProfileResultLabel: 'Contains Designation/Profile/Role/Industry',
    processingChunkSize: 1000,
    missingValues: ['', 'nan', 'null', 'none', 'n/a'],
    irrelevantNameTerms: ['test', 'abc', 'xyz', 'na', 'n/a', 'unknown', 'null', 'none', '---', '...', '.', 'dummy'],
    ignoredRoleProfileTerms: [],
    nameKeywordAcronyms: [
        'bd', 'bde', 'bdm', 'bpo', 'ca', 'ceo', 'cfo', 'chro', 'cma', 'cmo',
        'coo', 'cs', 'cto', 'cv', 'dba', 'erp', 'fmcg', 'gst', 'hr', 'ios',
        'it', 'ites', 'iti', 'kpo', 'mba', 'mca', 'mis', 'qa', 'qc', 'sap',
        'seo', 'ui', 'ux', 'vp'
    ],
    columnAliases: {
        name: ['name', 'candidate', 'full name'],
        mobile: ['mobile', 'phone', 'contact'],
        email: ['email', 'mail'],
        resume: ['resume', 'attached', 'cv'],
        gender: ['gender'],
        createdBy: ['createdby', 'created by'],
        skills: ['key_skills', 'key skills', 'skills'],
        designation: ['designation'],
        experience: ['total_experi', 'total experi', 'experience'],
        location: ['current_loca', 'current loca', 'location', 'city']
    },
    roleProfileTerms: [
        'profile', 'resume', 'cv', 'candidate', 'job', 'opening', 'vacancy',
        'walkin', 'walk-in', 'fresher', 'experienced', 'experience', 'exp',
        'male', 'female', 'senior', 'junior', 'lead', 'head', 'chief',
        'manager', 'assistant manager', 'deputy manager', 'general manager',
        'executive', 'senior executive', 'officer', 'coordinator', 'incharge',
        'in-charge', 'supervisor', 'team leader', 'associate', 'specialist',
        'consultant', 'analyst', 'trainee', 'intern', 'internship',
        'apprentice', 'director', 'founder', 'co founder', 'co-founder',
        'owner', 'partner', 'president', 'vice president', 'vp', 'ceo', 'cfo',
        'coo', 'cto', 'cmo', 'chro',
        'hr', 'human resource', 'human resources', 'recruiter', 'recruitment',
        'talent acquisition', 'hr executive', 'hr manager', 'hr recruiter',
        'sales', 'sales executive', 'sales manager', 'field sales',
        'area sales manager', 'regional sales manager', 'territory sales',
        'business development', 'business development executive',
        'business development manager', 'bd', 'bde', 'bdm', 'marketing',
        'marketing executive', 'marketing manager', 'digital marketing',
        'seo', 'social media', 'telecaller', 'telesales', 'inside sales',
        'customer support', 'customer care', 'customer service',
        'relationship manager', 'client servicing', 'account manager',
        'key account manager', 'front office', 'receptionist', 'counsellor',
        'counselor',
        'it', 'software', 'developer', 'engineer', 'software engineer',
        'software developer', 'programmer', 'web developer', 'frontend',
        'front end', 'backend', 'back end', 'full stack', 'fullstack',
        'java developer', 'python developer', 'php developer',
        'dot net developer', '.net developer', 'react developer',
        'angular developer', 'node developer', 'android developer',
        'ios developer', 'mobile developer', 'devops', 'cloud engineer',
        'network engineer', 'system administrator', 'database administrator',
        'dba', 'data entry', 'data operator', 'data analyst',
        'business analyst', 'data scientist', 'data engineer', 'mis',
        'mis executive', 'qa', 'qc', 'tester', 'test engineer',
        'software tester', 'automation tester', 'quality analyst',
        'product manager', 'project manager', 'scrum master',
        'finance', 'financial analyst', 'account', 'accounts', 'accountant',
        'account executive', 'accounts executive', 'accounts manager',
        'account assistant', 'audit', 'auditor', 'tax', 'taxation', 'gst',
        'tally', 'sap', 'erp', 'payroll', 'banker', 'banking', 'insurance',
        'ca', 'cs', 'cma', 'admin', 'administration', 'admin executive',
        'office assistant', 'back office', 'back office executive',
        'legal', 'lawyer', 'advocate', 'company secretary',
        'operations', 'operation', 'production', 'maintenance', 'quality',
        'quality control', 'quality engineer', 'purchase', 'procurement',
        'supply chain', 'logistics', 'warehouse', 'store', 'store keeper',
        'store incharge', 'inventory', 'dispatch', 'plant', 'operator',
        'machine operator', 'technician', 'fitter', 'welder', 'electrician',
        'plumber', 'mechanic', 'mechanical engineer', 'electrical engineer',
        'civil engineer', 'site engineer', 'service engineer',
        'design engineer', 'architect', 'interior designer', 'draftsman',
        'draughtsman',
        'doctor', 'nurse', 'pharmacist', 'physiotherapist', 'lab technician',
        'medical representative', 'teacher', 'faculty', 'professor',
        'lecturer', 'trainer', 'academic', 'graphic designer', 'ui designer',
        'ux designer', 'ui ux designer', 'video editor', 'content writer',
        'copywriter', 'chef', 'cook', 'steward', 'housekeeping', 'cashier',
        'retail', 'store manager', 'security guard', 'driver', 'delivery',
        'courier',
        'manufacturing', 'pharma', 'pharmaceutical', 'healthcare', 'hospital',
        'education', 'automobile', 'automotive', 'construction',
        'real estate', 'telecom', 'fmcg', 'chemical', 'textile', 'garment',
        'jewellery', 'jewelry', 'hospitality', 'hotel', 'restaurant',
        'travel', 'tourism', 'import export', 'export', 'agriculture',
        'food', 'beverage', 'ecommerce', 'e-commerce', 'fintech', 'ites',
        'bpo', 'kpo', 'media', 'advertising', 'oil', 'gas', 'energy',
        'power', 'solar', 'steel', 'cement', 'plastic', 'packaging',
        'printing', 'mba', 'mca', 'btech', 'b.tech', 'mtech', 'm.tech',
        'diploma', 'iti'
    ]
};
